# Generated by Django 3.0.2 on 2021-03-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mention',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
