# Generated by Django 3.0.2 on 2021-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210328_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='coinflip_bid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='account',
            name='coinflip_request_from',
            field=models.IntegerField(default=0),
        ),
    ]
